# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=1.0 --num_trial=1 --algorithm='dsgd' --device="cuda"
# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=1.0 --num_trial=1 --algorithm='dsgt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=1.0 --num_trial=1 --algorithm='dasagt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=1.0 --num_trial=1 --algorithm='dnasa' --device="cuda"

# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=10.0 --num_trial=1 --algorithm='dsgd' --device="cuda"
# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=10.0 --num_trial=1 --algorithm='dsgt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=10.0 --num_trial=1 --algorithm='dasagt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=10.0 --num_trial=1 --algorithm='dnasa' --device="cuda"

# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=5.0 --num_trial=1 --algorithm='dsgd' --device="cuda"
# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=5.0 --num_trial=1 --algorithm='dsgt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=5.0 --num_trial=1 --algorithm='dasagt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=5.0 --num_trial=1 --algorithm='dnasa' --device="cuda"

# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.5 --num_trial=1 --algorithm='dsgd' --device="cuda"
# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.5 --num_trial=1 --algorithm='dsgt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.5 --num_trial=1 --algorithm='dasagt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.5 --num_trial=1 --algorithm='dnasa' --device="cuda"

# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.1 --num_trial=1 --algorithm='dsgd' --device="cuda"
# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.1 --num_trial=1 --algorithm='dsgt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=1001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.1 --num_trial=1 --algorithm='dasagt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.1 --num_trial=1 --algorithm='dnasa' --device="cuda"

# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.05 --num_trial=1 --algorithm='dsgd' --device="cuda"
# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.05 --num_trial=1 --algorithm='dsgt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.05 --num_trial=1 --algorithm='dasagt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=0.05 --num_trial=1 --algorithm='dnasa' --device="cuda"

# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=50.0 --num_trial=1 --algorithm='dsgd' --device="cuda"
# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=50.0 --num_trial=1 --algorithm='dsgt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=50.0 --num_trial=1 --algorithm='dasagt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=50.0 --num_trial=1 --algorithm='dnasa' --device="cuda"

# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=100.0 --num_trial=1 --algorithm='dsgd' --device="cuda"
# mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=100.0 --num_trial=1 --algorithm='dsgt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=100.0 --num_trial=1 --algorithm='dasagt' --device="cuda"
mpirun -np 4 python run.py --data='cifar' --model='lenet' --updates=3001 --report=100 --comm_pattern='ring' --init_batch=1 --mini_batch=4 --step_type='diminishing' --k0=3 --beta=0.0228 --lr=100.0 --num_trial=1 --algorithm='dnasa' --device="cuda"